
DEVICE_ID=
DEVICE_SECRET=
API_BASE_URL=
REALM_NAME=
PERSISTENCY_PATH=persistency.d
INTERFACES_FOLDER=astarte-interfaces
PYTHONUNBUFFERED=1

EVENTS_DELAY_BASE_S=480
EVENTS_DELAY_DELTA_S=150
EVENTS_DURATION_BASE_S=10.0
EVENTS_DURATION_DELTA_S=2.5
