
export API_BASE_URL=
export REALM_NAME=
export DEVICE_ID=
export DEVICE_SECRET=
export PERSISTENCY_PATH=persistency.d
export INTERFACES_FOLDER=astarte-interfaces
export PYTHONUNBUFFERED=1

export EVENTS_DELAY_BASE_S=480
export EVENTS_DELAY_DELTA_S=150
export EVENTS_DURATION_BASE_S=10.0
export EVENTS_DURATION_DELTA_S=2.5

export WIFI_SCAN_RESULT_DELAY_UPDATE_S=7200
export CELLULAR_STATUS_DELAY_UPDATE_S=3600
